### ISSUE TITLE
No links exist/are visible

### ISSUE THREAD

**Issue by jacquesalbert** [sudomesh/disaster-radio-simulator#15]
I cloned the simulator and got it running but when I go to the visualizer I only see nodes, no links. This happens for any of the provided net_structures. No routing tables appear to have been populated, and messages do not travel between nodes, so it seems it's not a display issue. There really is no link.

Edit: Okay, I had one of my serial devices in the wrong spot. I CAN get messages out broadcast, it appears it's simply not populating routing tables and therefore not drawing links. Perhaps not an issue with the simulator but with the firmware. Or me.

**Comment by paidforby** [comment]
Hey @jacquesalbert glad you figured out part of your problem. A few things. Since I've been actively working on this simulator, I have had time to update the visualizer portion as I was updating the protocol, so much of the visualizer parts (i.e. drawing links and printing the routing tables) have fallen out of sync with the protocol. This is mostly due to switching from 6 byte addresses to 4 byte addresses as well as the removal of the need for routing table packets.

I'll push a commit shortly that will bring back the routing table packets that automate much of the route building. Currently to view the routing table you can execute `/lora` in the socat serial client after sending a broadcast messages to a node. You can also sended routed messages by starting a message with `@<noda address> <message>`. I'll try to resolve the issues you pointed soon.

Sorry about the confusion, the simulator is very much a work in progress.

**Comment by jacquesalbert** [comment]
No problem, thank you for letting me know! I will give it a try again with your updates when I get a chance.

**Comment by paidforby** [comment]
I believe that 89f7c31 may address most of your concerns. The routing table is again visible in the visualizer (assuming you have routing table packets enabled, which they now are by default). Also, the dashed lines are again drawn when a packet is directed/routed to a destination. 

Currently "links" or routes are only visible when a packet is being transmitted, i eventually might like to add permanent, semi-transparent lines for existing routes between neighbors that "light-up" or become solid when they are transmitted along.

I also need to devise a "better" / "less-hacky" method for the visualizer to access the routing table. Currently, it "listens" for routing table packets, but since adding the option for reactive routing that doesn't require these packets, it is possible that routing tables may be built without ever transmitting a routing table packet.

Anyway, if these recent commits address your issue @jacquesalbert then go ahead and close this issue.

**Comment by jacquesalbert** [comment]
Thank you for working on this! I just gave it a try and had a slew of compile errors that weren't there before. I also attempted to run fetch_deps and it now gives an error when trying to checkout LoRaLayer2 saying the reference is not a valid tree.

**Comment by paidforby** [comment]
Hmmm. I must have copied in the wrong commit tag for LoRaLayer2 into fetch_deps. I just updated to the latest commit on the DSR branch of LoRaLayer2, https://github.com/sudomesh/LoRaLayer2/tree/DSR. Give it another try, fetch_deps is working for me now. If you didn't successfully fetch LoRaLayer2, that would have caused a lot of compiler errors.

**Comment by jacquesalbert** [comment]
That did the trick. fetch_deps grabbed a valid version, everything compiled no problem. The sim runs and builds routing tables using periodic broadcasts, packets can be broadcast or directed to specific destinations and the route will be displayed.

Thanks!
